// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"users/users/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/users/wechat/auth",
				Handler: WechatAuthHandler(serverCtx),
			},
		},
	)
}
