// Code generated by goctl. DO NOT EDIT.
package types

type WechatAuthRequest struct {
	JsCode    string `json:"jscode"`
	AvatarUrl string `json:"avatar_url"`
	Nickname  string `json:"nickname"`
}

type ResponseStatus struct {
	Code int    `json:"code"`
	Msg  string `json:"msg,optional"`
}

type User struct {
	UserId    int    `json:"user_id"`
	Nickname  string `json:"nickname"`
	AvatarUrl string `json:"avatar_url"`
}

type WechatAuthResponse struct {
	Status   ResponseStatus `json:"status"`
	Data     User           `json:"user,optional"`
	AuthCode string         `json:"auth_code"`
}
